-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE Availability (
--     id SERIAL PRIMARY KEY,
--     day_of_week VARCHAR(10),
--     start_time TIME,
--     end_time TIME,
--     user_id UUID
-- );
